
services:
  backend:
    build: ./backend
    container_name: interviewiq-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:17

    container_name: interviewiq-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rohit1234
      POSTGRES_DB: interviewiq

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d interviewiq"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: interviewiq-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
    build:
      context: ./backend

    container_name: interviewiq-celery

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    command: celery -A app.core.celery_app worker -l info

    restart: unless-stopped
  
  flower:
    build:
      context: ./backend

    container_name: interviewiq-flower

    env_file:
      - ./backend/.env

    command: celery -A app.core.celery_app flower --port=5555

    ports:
      - "5555:5555"

    depends_on:
      - celery

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: interviewiq-frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: