"""create interview question insights table

Revision ID: 2e06529fe5cd
Revises: 24482603fd91
Create Date: 2026-07-24 12:48:19.884458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e06529fe5cd'
down_revision: Union[str, Sequence[str], None] = '24482603fd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_question_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_question_id', sa.Integer(), nullable=False),
    sa.Column('ideal_answer', sa.String(), nullable=False),
    sa.Column('key_learning_points', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_question_id')
    )
    op.create_index(op.f('ix_interview_question_insights_id'), 'interview_question_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_question_insights_id'), table_name='interview_question_insights')
    op.drop_table('interview_question_insights')
    # ### end Alembic commands ###
