""" create interview report

Revision ID: cce0fc9c2cae
Revises: a5080e29d897
Create Date: 2026-07-21 21:59:31.382547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cce0fc9c2cae'
down_revision: Union[str, Sequence[str], None] = 'a5080e29d897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('communication_score', sa.Float(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('problem_solving_score', sa.Float(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('hiring_recommendation', sa.Text(), nullable=False),
    sa.Column('improvement_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_reports_id'), 'interview_reports', ['id'], unique=False)
    op.create_index(op.f('ix_interview_reports_interview_id'), 'interview_reports', ['interview_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_reports_interview_id'), table_name='interview_reports')
    op.drop_index(op.f('ix_interview_reports_id'), table_name='interview_reports')
    op.drop_table('interview_reports')
    # ### end Alembic commands ###
