"""added role to users

Revision ID: d2896d2911f6
Revises: f0cbd45fb4cb
Create Date: 2026-07-18 01:15:35.718675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2896d2911f6'
down_revision: Union[str, Sequence[str], None] = 'f0cbd45fb4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "users",
    sa.Column(
        "role",
        sa.String(length=20),
        nullable=False,
        server_default="candidate",
    ),
)
    op.alter_column(
        "users",
        "role",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
